#!/bin/bash
# This program is to easily install, update or set DOS76
if [ "$EUID" -eq 0 ]; then
    echo -e "\e[1;31mDon't run as root\e[0m"
    exit 0
fi

case $1 in

install)
    echo -e "\e[1;34mInstalling DOS76\e[0m"
    bash dos76_install_helper.sh
    ;;

update | get)
    echo -e "\e[1;34mUpdating DOS76\e[0m"
    bash dos76_update_helper.sh
    ;;

set)
    echo -e "\e[1;34mSetting DOS76\e[0m"
    bash dos76_set_helper.sh
    ;;

--help)
    echo -e "\e[1;34mUsage: DOS76 [install|update|set|--help]\e[0m"
    echo -e "\e[1;34minstall: DOS76 install\e[0m"
    echo -e "\e[1;34mupdate: DOS76 update\e[0m"
    echo -e "\e[1;34mset: DOS76 set\e[0m"
    echo -e "\e[1;34m help (this message): DOS76 --help\e[0m"
    ;;
*)
    echo -e"\e[1;31mInvalid option!\e[0m"
    ;;
esac
