#!/bin/bash
# This program is to easily install, update or set DOS76
if [ "$EUID" -eq 0 ]; then
    echo -e -e "\e[1;31mDon't run as root\e[0m"
    exit 0
fi

case $1 in

install)
    echo -e "\e[1;34mInstalling DOS76\e[0m"
    ;;

update)
    echo -e "\e[1;34mUpdating DOS76\e[0m"
    ;;

set)
    echo -e "\e[1;34mSetting DOS76\e[0m"
    ;;

--help)
    echo -e -e "\e[1;34mUsage: ./DOS76.sh [install|update|set]\e[0m"
    echo -e -e "\e[1;34minstall: install DOS76\e[0m"
    echo -e -e "\e[1;34mupdate: update DOS76\e[0m"
    echo -e -e "\e[1;34mset: set DOS76\e[0m"
    ;;
*)
    echo -e"\e[1;31mInvalid option!\e[0m"
    ;;
esac
