// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref('app.update.lastUpdateTime.addon-background-update-timer', 1635153086);
user_pref('app.update.lastUpdateTime.search-engine-update-timer', 1635152846);
user_pref('app.update.lastUpdateTime.services-settings-poll-changes', 1635152966);
user_pref('app.update.lastUpdateTime.telemetry_modules_ping', 1635153483);
user_pref('app.update.lastUpdateTime.xpi-signature-verification', 1635153206);
user_pref('browser.cache.disk.amount_written', 13062);
user_pref('browser.cache.disk.capacity', 942080);
user_pref('browser.cache.disk.filesystem_reported', 1);
user_pref(
  'calendar.list.sortOrder',
  '92189a68-62a0-4732-8124-0a5938c8cb74 54742cbf-0441-411e-86cd-f6e8f6fdc24b'
);
user_pref(
  'calendar.registry.54742cbf-0441-411e-86cd-f6e8f6fdc24b.calendar-main-in-composite',
  true
);
user_pref(
  'calendar.registry.54742cbf-0441-411e-86cd-f6e8f6fdc24b.calendarSyncState',
  '{"initialLoad":false,"resultPage":0,"lastModifiedTime":"2021-08-26T16:04:50Z"}'
);
user_pref('calendar.registry.54742cbf-0441-411e-86cd-f6e8f6fdc24b.calendarSyncVersion', '0.7.7.5');
user_pref('calendar.registry.54742cbf-0441-411e-86cd-f6e8f6fdc24b.name', 'cl01\\2018NPbscdo');
user_pref(
  'calendar.registry.54742cbf-0441-411e-86cd-f6e8f6fdc24b.tasksSyncState',
  '{"initialLoad":true,"resultPage":0,"lastModifiedTime":""}'
);
user_pref('calendar.registry.54742cbf-0441-411e-86cd-f6e8f6fdc24b.type', 'owl');
user_pref(
  'calendar.registry.54742cbf-0441-411e-86cd-f6e8f6fdc24b.uri',
  'owl://cl01%5C2018NPbscdo@webmail.bwzt.ch/'
);
user_pref('calendar.registry.92189a68-62a0-4732-8124-0a5938c8cb74.calendar-main-default', true);
user_pref(
  'calendar.registry.92189a68-62a0-4732-8124-0a5938c8cb74.calendar-main-in-composite',
  true
);
user_pref('calendar.registry.92189a68-62a0-4732-8124-0a5938c8cb74.disabled', true);
user_pref('calendar.registry.92189a68-62a0-4732-8124-0a5938c8cb74.name', 'Home');
user_pref('calendar.registry.92189a68-62a0-4732-8124-0a5938c8cb74.type', 'storage');
user_pref('calendar.registry.92189a68-62a0-4732-8124-0a5938c8cb74.uri', 'moz-storage-calendar://');
user_pref('calendar.timezone.local', 'Europe/Zurich');
user_pref('calendar.ui.version', 3);
user_pref('datareporting.policy.dataSubmissionPolicyAcceptedVersion', 1);
user_pref('datareporting.policy.dataSubmissionPolicyNotifiedTime', '1630326734525');
user_pref('extensions.activeThemeID', 'maxfrei@web.de');
user_pref('extensions.blocklist.pingCountVersion', -1);
user_pref('extensions.databaseSchema', 32);
user_pref('extensions.getAddons.cache.lastUpdate', 1635153086);
user_pref('extensions.getAddons.databaseSchema', 6);
user_pref('extensions.incognito.migrated', true);
user_pref('extensions.lastAppBuildId', '20210802223056');
user_pref('extensions.lastAppVersion', '78.13.0');
user_pref('extensions.lastPlatformVersion', '78.13.0');
user_pref('extensions.owl.first_run', '1630326806815');
user_pref(
  'extensions.owl.ticket',
  '{"json":"{\\"licenseType\\":\\"paid\\",\\"version\\":78,\\"start\\":\\"2021-08-28T00:00:00.000Z\\",\\"end\\":\\"2022-08-28T00:00:00.000Z\\",\\"refresh\\":\\"2021-11-01T06:38:23.647Z\\",\\"email\\":\\"domi.schwaiger04@gmail.com\\"}","signature":"2a563e2a5149ab7c815d00804f41910ed15289ecc0aacd5c8bf56f97314ed95a91d101bdde834441656f1e2a464e5c4478ab3545dc0c2dffeb87b3fe8e2b838f162036fbcda11e4d033e8419ab21ab2e3114c69194f8f1636486cc0ae4d56e1d48095efdb713a0e4f0723da9bb3094c06f9c84888a43119a334dd705f8dda47efb6d7a2e8b373ca61ff4aea644708d7a2b8716388c3db8f0001a629a4ba549f4738855d282c87aed902ba446b3fe2bb8bf008742ffa705e6c528ed02bd209d844a716f37955a3add422606daba334216a97c27d02ffb5864218f57ff42981f702057d123e7917689efc8ddba85f539d1a6d81acb383ba886b1a4ec5588e0e6df"}'
);
user_pref('extensions.owl.useGlobalPreferredServer.owl', true);
user_pref('extensions.owl.useGlobalPreferredServer.owl-eas', true);
user_pref('extensions.owl.useGlobalPreferredServer.owl-ews', true);
user_pref('extensions.pendingOperations', true);
user_pref('extensions.systemAddonSet', '{"schema":1,"addons":{}}');
user_pref('extensions.ui.dictionary.hidden', true);
user_pref('extensions.ui.extension.hidden', false);
user_pref('extensions.ui.lastCategory', 'addons://list/extension');
user_pref('extensions.ui.locale.hidden', true);
user_pref('extensions.ui.theme.hidden', false);
user_pref('extensions.webextensions.ExtensionStorageIDB.migrated.owl@beonex.com', true);
user_pref(
  'extensions.webextensions.uuids',
  '{"wetransfer@extensions.thunderbird.net":"c0326b5c-70e0-426c-8a3e-c805ab83741f","default-theme@mozilla.org":"be377ea4-4e88-4230-9847-d19766482c9b","google@search.mozilla.org":"1f46a74e-f369-4eec-806e-c3714dcad3be","amazondotcom@search.mozilla.org":"285aaff1-fa54-437f-a0df-06a0f092f1b2","bing@search.mozilla.org":"f74eee17-f778-4b41-8276-5040a0ff4954","ddg@search.mozilla.org":"65984311-85e2-4284-b0c6-642e976ee25e","wikipedia@search.mozilla.org":"d4ec9f75-f3a6-4bb6-aa47-039e2d174b63","owl@beonex.com":"27e45e47-b7a6-47f8-820b-f111ccedf56e","maxfrei@web.de":"2246fbbb-f17b-4585-ad01-c39ef67ef7f4"}'
);
user_pref('font.internaluseonly.changed', false);
user_pref('idle.lastDailyNotification', 1635154046);
user_pref('ldap_2.servers.history.uid', '46680784-964a-460a-bd17-ec1970329653');
user_pref('ldap_2.servers.kantiwattwilchKontakte.description', 'kantiwattwil.ch Kontakte');
user_pref('ldap_2.servers.kantiwattwilchKontakte.dirType', 101);
user_pref('ldap_2.servers.kantiwattwilchKontakte.filename', 'abook-1.sqlite');
user_pref('ldap_2.servers.kantiwattwilchKontakte.uid', 'be30c5c3-0f5f-4a0e-a53f-1ce2338d6261');
user_pref('ldap_2.servers.pab.uid', '7fdf6fd1-dd99-4009-a908-add42d7fbd72');
user_pref('mail.ab_remote_content.migrated', 1);
user_pref('mail.account.account1.identities', 'id1');
user_pref('mail.account.account1.server', 'server1');
user_pref('mail.account.account2.server', 'server2');
user_pref('mail.account.account3.identities', 'id2');
user_pref('mail.account.account3.server', 'server3');
user_pref('mail.account.lastKey', 3);
user_pref('mail.accountmanager.accounts', 'account1,account2,account3');
user_pref('mail.accountmanager.defaultaccount', 'account1');
user_pref('mail.accountmanager.localfoldersserver', 'server2');
user_pref('mail.append_preconfig_smtpservers.version', 2);
user_pref('mail.compose.attach.dir', '/home/quio/Desktop');
user_pref('mail.default_charsets.migrated', 1);
user_pref('mail.folder.views.version', 1);
user_pref(
  'mail.identity.id1.archive_folder',
  'imap://domi.schwaiger04%40gmail.com@imap.gmail.com/[Gmail]/All mail'
);
user_pref('mail.identity.id1.archives_folder_picker_mode', '1');
user_pref('mail.identity.id1.doBcc', false);
user_pref(
  'mail.identity.id1.draft_folder',
  'imap://domi.schwaiger04%40gmail.com@imap.gmail.com/[Gmail]/Drafts'
);
user_pref('mail.identity.id1.drafts_folder_picker_mode', '1');
user_pref(
  'mail.identity.id1.fcc_folder',
  'imap://domi.schwaiger04%40gmail.com@imap.gmail.com/[Gmail]/Sent Mail'
);
user_pref('mail.identity.id1.fcc_folder_picker_mode', '1');
user_pref('mail.identity.id1.fullName', 'Dominik Schwaiger');
user_pref('mail.identity.id1.reply_on_top', 1);
user_pref('mail.identity.id1.smtpServer', 'smtp1');
user_pref(
  'mail.identity.id1.stationery_folder',
  'imap://domi.schwaiger04%40gmail.com@imap.gmail.com/Templates'
);
user_pref('mail.identity.id1.tmpl_folder_picker_mode', '0');
user_pref('mail.identity.id1.useremail', 'domi.schwaiger04@gmail.com');
user_pref('mail.identity.id1.valid', true);
user_pref('mail.identity.id2.archive_folder', 'owl://cl01%5C2018NPbscdo@webmail.bwzt.ch/Archives');
user_pref('mail.identity.id2.doBcc', false);
user_pref(
  'mail.identity.id2.draft_folder',
  'owl://cl01%5C2018NPbscdo@webmail.bwzt.ch/Entw%C3%BCrfe'
);
user_pref('mail.identity.id2.drafts_folder_picker_mode', '1');
user_pref(
  'mail.identity.id2.fcc_folder',
  'owl://cl01%5C2018NPbscdo@webmail.bwzt.ch/Gesendete%20Elemente'
);
user_pref('mail.identity.id2.fcc_folder_picker_mode', '1');
user_pref('mail.identity.id2.fullName', 'Dominik Schwaiger');
user_pref('mail.identity.id2.stationery_folder', 'mailbox://nobody@Local%20Folders/Templates');
user_pref('mail.identity.id2.useremail', 'dominik.schwaiger@kantiwattwil.ch');
user_pref('mail.identity.id2.valid', true);
user_pref('mail.imap.chunk_size', 90112);
user_pref('mail.imap.min_chunk_size_threshold', 135168);
user_pref(
  'mail.last_msg_movecopy_target_uri',
  'owl://cl01%5C2018NPbscdo@webmail.bwzt.ch/Schule/Maturaarbeit'
);
user_pref('mail.openMessageBehavior.version', 1);
user_pref('mail.purge.ask', false);
user_pref('mail.purge_threshhold_mb', 20);
user_pref('mail.purge_threshold_migrated', true);
user_pref('mail.root.imap', '/home/quio/.thunderbird/4adu5jru.default-release/ImapMail');
user_pref('mail.root.imap-rel', '[ProfD]ImapMail');
user_pref('mail.root.none', '/home/quio/.thunderbird/4adu5jru.default-release/Mail');
user_pref('mail.root.none-rel', '[ProfD]Mail');
user_pref(
  'mail.root.webaccount',
  '/home/quio/.thunderbird/4adu5jru.default-release/webaccountMail'
);
user_pref('mail.root.webaccount-rel', '[ProfD]webaccountMail');
user_pref('mail.server.server1.authMethod', 10);
user_pref('mail.server.server1.check_new_mail', true);
user_pref('mail.server.server1.clientid', '6870146d-cf9f-4ef1-9e73-0e62f9a48321');
user_pref(
  'mail.server.server1.directory',
  '/home/quio/.thunderbird/4adu5jru.default-release/ImapMail/imap.gmail.com'
);
user_pref('mail.server.server1.directory-rel', '[ProfD]ImapMail/imap.gmail.com');
user_pref('mail.server.server1.force_select', 'no-auto');
user_pref('mail.server.server1.hostname', 'imap.gmail.com');
user_pref('mail.server.server1.is_gmail', true);
user_pref('mail.server.server1.lastFilterTime', 27252916);
user_pref('mail.server.server1.login_at_startup', true);
user_pref('mail.server.server1.max_cached_connections', 5);
user_pref('mail.server.server1.moveTargetMode', 1);
user_pref('mail.server.server1.name', 'domi.schwaiger04@gmail.com');
user_pref('mail.server.server1.namespace.personal', '""');
user_pref('mail.server.server1.nextFilterTime', 27252926);
user_pref('mail.server.server1.oauth2.issuer', 'accounts.google.com');
user_pref('mail.server.server1.oauth2.scope', 'https://mail.google.com/');
user_pref('mail.server.server1.port', 993);
user_pref(
  'mail.server.server1.serverIDResponse',
  '("name" "GImap" "vendor" "Google, Inc." "support-url" "https://support.google.com/mail" "version" "gmail_imap_211018.08_p0" "remote-host" "213.196.183.54")'
);
user_pref('mail.server.server1.socketType', 3);
user_pref(
  'mail.server.server1.spamActionTargetAccount',
  'imap://domi.schwaiger04%40gmail.com@imap.gmail.com'
);
user_pref(
  'mail.server.server1.spamActionTargetFolder',
  'imap://domi.schwaiger04%40gmail.com@imap.gmail.com/[Gmail]/Spam'
);
user_pref('mail.server.server1.storeContractID', '@mozilla.org/msgstore/berkeleystore;1');
user_pref('mail.server.server1.timeout', 29);
user_pref('mail.server.server1.type', 'imap');
user_pref('mail.server.server1.userName', 'domi.schwaiger04@gmail.com');
user_pref(
  'mail.server.server2.directory',
  '/home/quio/.thunderbird/4adu5jru.default-release/Mail/Local Folders'
);
user_pref('mail.server.server2.directory-rel', '[ProfD]Mail/Local Folders');
user_pref('mail.server.server2.hostname', 'Local Folders');
user_pref('mail.server.server2.lastFilterTime', 27252916);
user_pref('mail.server.server2.name', 'Local Folders');
user_pref('mail.server.server2.nextFilterTime', 27252926);
user_pref('mail.server.server2.spamActionTargetAccount', 'mailbox://nobody@Local%20Folders');
user_pref('mail.server.server2.storeContractID', '@mozilla.org/msgstore/berkeleystore;1');
user_pref('mail.server.server2.type', 'none');
user_pref('mail.server.server2.userName', 'nobody');
user_pref('mail.server.server3.addedCalendar', true);
user_pref('mail.server.server3.addressBook', 'be30c5c3-0f5f-4a0e-a53f-1ce2338d6261');
user_pref(
  'mail.server.server3.directory',
  '/home/quio/.thunderbird/4adu5jru.default-release/webaccountMail/webmail.bwzt.ch'
);
user_pref('mail.server.server3.directory-rel', '[ProfD]webaccountMail/webmail.bwzt.ch');
user_pref('mail.server.server3.hostname', 'webmail.bwzt.ch');
user_pref('mail.server.server3.lastFilterTime', 27252916);
user_pref('mail.server.server3.max_concurrency_measured', 12);
user_pref('mail.server.server3.moveTargetMode', 1);
user_pref('mail.server.server3.name', 'dominik.schwaiger@kantiwattwil.ch');
user_pref('mail.server.server3.nextFilterTime', 27252926);
user_pref('mail.server.server3.owa_url', 'https://webmail.bwzt.ch/owa/');
user_pref('mail.server.server3.secondsToLeaveUnavailable', 31536000);
user_pref(
  'mail.server.server3.spamActionTargetAccount',
  'owl://cl01%5C2018NPbscdo@webmail.bwzt.ch'
);
user_pref(
  'mail.server.server3.spamActionTargetFolder',
  'owl://cl01%5C2018NPbscdo@webmail.bwzt.ch/Junk-E-Mail'
);
user_pref('mail.server.server3.storeContractID', '@mozilla.org/msgstore/berkeleystore;1');
user_pref('mail.server.server3.subtype', 'owa');
user_pref('mail.server.server3.timeFoundUnavailable', 1630339853);
user_pref('mail.server.server3.trash_folder_name', 'Gel%C3%B6schte%20Elemente');
user_pref('mail.server.server3.type', 'owl');
user_pref('mail.server.server3.userName', 'cl01\\2018NPbscdo');
user_pref('mail.smtpserver.smtp1.authMethod', 10);
user_pref('mail.smtpserver.smtp1.clientid', '7c21b5fd-6fdf-45c0-9c8e-357b9a40b2f6');
user_pref('mail.smtpserver.smtp1.description', 'Google Mail');
user_pref('mail.smtpserver.smtp1.hostname', 'smtp.gmail.com');
user_pref('mail.smtpserver.smtp1.oauth2.issuer', 'accounts.google.com');
user_pref('mail.smtpserver.smtp1.oauth2.scope', 'https://mail.google.com/');
user_pref('mail.smtpserver.smtp1.port', 465);
user_pref('mail.smtpserver.smtp1.try_ssl', 3);
user_pref('mail.smtpserver.smtp1.username', 'domi.schwaiger04@gmail.com');
user_pref('mail.smtpservers', 'smtp1');
user_pref('mail.spam.version', 1);
user_pref('mail.startup.enabledMailCheckOnce', true);
user_pref('mail.ui-rdf.version', 23);
user_pref('mailnews.database.global.datastore.id', '1ee496b4-2ec1-4d20-8707-d1cf9b63b10');
user_pref(
  'mailnews.database.global.views.conversation.columns',
  '{"selectCol":{"visible":false,"ordinal":"1"},"threadCol":{"visible":true,"ordinal":"3"},"flaggedCol":{"visible":true,"ordinal":"5"},"attachmentCol":{"visible":false,"ordinal":"7"},"subjectCol":{"visible":true,"ordinal":"9"},"unreadButtonColHeader":{"visible":false,"ordinal":"11"},"senderCol":{"visible":false,"ordinal":"13"},"recipientCol":{"visible":false,"ordinal":"15"},"correspondentCol":{"visible":true,"ordinal":"17"},"junkStatusCol":{"visible":false,"ordinal":"19"},"receivedCol":{"visible":false,"ordinal":"21"},"dateCol":{"visible":true,"ordinal":"23"},"statusCol":{"visible":false,"ordinal":"25"},"sizeCol":{"visible":false,"ordinal":"27"},"tagsCol":{"visible":false,"ordinal":"29"},"accountCol":{"visible":false,"ordinal":"31"},"priorityCol":{"visible":false,"ordinal":"33"},"unreadCol":{"visible":false,"ordinal":"35"},"totalCol":{"visible":false,"ordinal":"37"},"locationCol":{"visible":true,"ordinal":"39"},"idCol":{"visible":false,"ordinal":"41"},"deleteCol":{"visible":false,"ordinal":"43"}}'
);
user_pref('mailnews.filters.migration78', true);
user_pref('mailnews.headers.extraAddonHeaders', 'autocrypt openpgp');
user_pref('mailnews.quotingPrefs.version', 1);
user_pref('mailnews.start_page_override.mstone', '78.13.0');
user_pref('mailnews.tags.$label1.color', '#FF0000');
user_pref('mailnews.tags.$label1.tag', 'Important');
user_pref('mailnews.tags.$label2.color', '#FF9900');
user_pref('mailnews.tags.$label2.tag', 'Work');
user_pref('mailnews.tags.$label3.color', '#009900');
user_pref('mailnews.tags.$label3.tag', 'Personal');
user_pref('mailnews.tags.$label4.color', '#3333FF');
user_pref('mailnews.tags.$label4.tag', 'To Do');
user_pref('mailnews.tags.$label5.color', '#993399');
user_pref('mailnews.tags.$label5.tag', 'Later');
user_pref('mailnews.tags.version', 2);
user_pref('messenger.save.dir', '/home/quio/OneDriveKanti/Ausbilding/Gymnasium/4NPb/Wichtiges');
user_pref('places.database.lastMaintenance', 1635154046);
user_pref('places.history.expiration.transient_current_max_pages', 112348);
user_pref('privacy.purge_trackers.date_in_cookie_database', '0');
user_pref('security.remote_settings.crlite_filters.checked', 1635152966);
user_pref('security.remote_settings.intermediates.checked', 1635152966);
user_pref('security.sandbox.plugin.tempDirSuffix', '380e433f-5f00-47a1-b8e2-eadae65389cb');
user_pref('services.blocklist.addons.checked', 1634895257);
user_pref('services.blocklist.pinning.checked', 1635152966);
user_pref('services.settings.clock_skew_seconds', 0);
user_pref('services.settings.last_etag', '"1635152250869"');
user_pref('services.settings.last_update_seconds', 1635152966);
user_pref('services.settings.main.anti-tracking-url-decoration.last_check', 1635152966);
user_pref('services.settings.main.hijack-blocklists.last_check', 1635152966);
user_pref('services.settings.main.language-dictionaries.last_check', 1635152966);
user_pref('services.settings.main.search-config.last_check', 1635152966);
user_pref('services.settings.main.search-default-override-allowlist.last_check', 1635152966);
user_pref('services.settings.main.sites-classification.last_check', 1635152966);
user_pref('services.settings.main.url-classifier-skip-urls.last_check', 1635152966);
user_pref('services.settings.security.onecrl.checked', 1635152966);
user_pref('signon.importedFromSqlite', true);
user_pref('storage.vacuum.last.index', 1);
user_pref('storage.vacuum.last.places.sqlite', 1633072183);
user_pref('toolkit.telemetry.cachedClientID', '4604e212-5ee0-4cc3-a8aa-a3556f59510f');
user_pref('toolkit.telemetry.previousBuildID', '20210802223056');
user_pref('ui.systemUsesDarkTheme', 1);
